all: server
server: http_parser.c http_request_parse.cpp net.cpp http_request.c request_parser.cpp server_http.cpp util.cpp request.cpp http_response.c callback.cpp pugixml.cpp
		g++ http_parser.c http_request_parse.cpp net.cpp http_request.c request_parser.cpp server_http.cpp util.cpp request.cpp http_response.c callback.cpp pugixml.cpp -o server
