all: server
server: http_parser.c http_request_parse.cpp net.cpp http_request.c request_parser.cpp server_airplay.cpp util.cpp request.cpp http_response.c callback.cpp pugixml.cpp base64.hpp Plist.cpp PlistDate.cpp pugiconfig.hpp
		g++ http_parser.c http_request_parse.cpp net.cpp http_request.c request_parser.cpp server_airplay.cpp util.cpp request.cpp http_response.c callback.cpp pugixml.cpp base64.hpp Plist.cpp PlistDate.cpp pugiconfig.hpp -I../include -o server
